# Generated by Django 5.1.1 on 2024-09-24 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_remove_patient_email_remove_patient_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='height',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='weight',
        ),
    ]
