# Generated by Django 5.1.1 on 2024-09-24 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_remove_patient_height_remove_patient_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='date_of_birth',
        ),
    ]
