# Generated by Django 5.1.1 on 2024-09-24 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_remove_patient_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='gender',
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='location',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.TextField(),
        ),
    ]
